config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'

  resources :movies, only: [:index, :show]
  resources :users, only: [:show]
  resources :categories, only: [:create, :destroy] do
    collection do
      post :like
      post :unlike
    end
  end

  delete '/remove_like/:id' => "categories#remove_like"
  get '/rate' => "movies#rate"
  get "search" => "search#search"
  get 'search/typeahead/:term' => 'search#typeahead'
  get "movies/:id" => "movies#show_simply"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many  :category_users
  has_many :categories, through: :category_users
  has_many :rateds
  def admin?
    self.admin
  end

  after_create :add_event
  def add_event
    # Create a client object.
    client = PredictionIO::EventClient.new(ENV["PIO_ACCESS_KEY"], ENV["PIO_EVENT_SERVER_URL"])

    # Create a new user
    client.create_event(
      '$set',
      'user',
      self.id.to_s
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @categories = Category.all.where.not(id: current_user.category_users.pluck(:category_id).uniq)
    @ratings = Movie.where(id: current_user.rateds.pluck(:movie_id))
    @category_users = current_user.category_users.like
    @un_category_users = current_user.category_users.un_like
  end
end

app/views/users/show.html.erb
<% @page_title = 'MovieLens Demo' %>
<div class="jumbotron">
  <div class="container">
    <p>User info</p>
  </div>
</div>
<div class="container">
  <% if !current_user.admin? %>
    <h1>List Movie Rating</h1> 
    <div class="owl-carousel">
      <% @ratings.each do |movie| %>
        <% if movie %>
          <div>
            <div class="movie-thumbnail">
              <div class="image">
                <%= link_to image_tag(movie.poster_url, alt: movie.title), movie %>
              </div>
              <div class="title">
                <h4>
                  <%= link_to movie.title, movie, "data-toggle" => "tooltip", title: movie.title %>
                </h4>
              </div>
              <%= render 'movies/details', movie: movie %>
            </div>
          </div>
        <% end -%>
      <% end -%>
    </div>
    <h1>List Like</h1>
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Delete</th>
      </tr>
      <% @category_users.each do |c| %>
        <tr>
          <td><%= c.category.try(:name) %></td>
          <td><%= link_to "Delete", "/remove_like/" + c.id.to_s, method: :delete %></td>
        </tr>
      <% end -%>
    </table>
    <h1>List Unlike</h1>
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Delete</th>
      </tr>
      <% @un_category_users.each do |c| %>
        <tr>
          <td><%= c.category.try(:name) %></td>
          <td><%= link_to "Delete", "/remove_like/" + c.id.to_s, method: :delete %></td>
        </tr>
      <% end -%>
    </table>
    <h1>Add Like</h1>
    <%= form_tag(like_categories_path, :method=>'post', :multipart => true) do %>
      <div class="form-group">
        <label>Name</label>
        <select name="category" class="form-control">
          <% @categories.each do |c| %>
            <option value="<%= c.id %>"><%= c.name %></option>
          <% end -%>
        </select>
      </div>
      <button type="submit" class="btn btn-default">Add</button>
    <% end -%>
    <h1>Add Unlike</h1>
    <%= form_tag(unlike_categories_path, :method=>'post', :multipart => true) do %>
    <div class="form-group">
      <label>Name</label>
      <select name="category" class="form-control">
        <% @categories.each do |c| %>
          <option value="<%= c.id %>"><%= c.name %></option>
        <% end -%>
      </select>
    </div>
    <button type="submit" class="btn btn-default">Add</button>
    <% end -%>
  <% else %>
    <h1>List Category</h1>
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Delete</th>
      </tr>
      <% @categories.each do |c| %>
        <tr>
          <td><%= c.try(:name) %></td>
          <td><%= link_to "Delete", category_path(c.id), method: :delete %></td>
        </tr>
      <% end -%>
    </table>
    <h1>Add new category</h1>
    <%= form_tag(categories_path, :method=>'post', :multipart => true) do %>
      <div class="form-group">
        <label>Name</label>
        <input type="text" name="category" class="form-control">
      </div>
      <button type="submit" class="btn btn-default" class="form-control">Create</button>
    <% end -%>
  <% end -%>
</div>